FROM node:22 AS base

ENV PATH=/app/node_modules/.bin:$PATH
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=web
WORKDIR /app
COPY . .
RUN turbo prune --scope=${APP} --docker

FROM base AS installer
ARG APP=web
WORKDIR /app
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json  ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY .npmrc ./
COPY packages/ ./packages/
RUN pnpm install --filter ${APP}

#   "build" "pnpm --recursive run build && <name> build" in package.json or manualy build the dependency


FROM base AS  builder
ARG APP=web
ARG NEXT_PUBLIC_FRONTEND_URL
ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_WS_SERVER_URL
WORKDIR /app
ENV NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
ENV NEXT_PUBLIC_WS_SERVER_URL=${NEXT_PUBLIC_FRONTEND_URL}
COPY --from=installer /app ./
COPY --from=installer /app/node_modules ./node_modules
WORKDIR /app/apps/${APP}
RUN pnpm run build
RUN pnpm --filter=${APP} deploy /outdir --prod

FROM node:22-slim AS runner
ARG APP=web
WORKDIR /app
COPY --from=builder /app/apps/${APP}/outdir/. ./apps/${APP}/
WORKDIR /app/apps/${APP}
EXPOSE 3000
CMD ["node", ".next/standalone/server.js"]