services:
  urlshortner-web:
    image: ${DOCKER_USERNAME}/url-web:latest
    container_name: urlshortner-web
    env_file:
      - env.compose      
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "1"  
    restart: unless-stopped

  analytics-web:
    image: ${DOCKER_USERNAME}/url-analytics:latest
    container_name: analytics
    env_file:
      - env.compose      
    ports:
      - "3006:3006"
    networks:
      - rabbitmq_net  
    deploy:
      resources:
        limits:
          cpus: "1"  
    restart: unless-stopped    

  data-collector:
    image: ${DOCKER_USERNAME}/url-data-collector:latest
    container_name: data-collector
    env_file:
      - env.compose  
    ports:
      - "3012:3012"
    restart: unless-stopped
    networks:
      - rabbitmq_net
    deploy:
      resources:
        limits:
          cpus: "0.25"  
    depends_on:
      - rabbitmq
      - nats
  
  ws-server:
    image: ${DOCKER_USERNAME}/url-ws-server:latest
    container_name: ws-server
    
    env_file:
      - env.compose  
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq
      - nats

  http-server:
    image: ${DOCKER_USERNAME}/url-http-server:latest
    container_name: http-server
    env_file:
      - env.compose  
    deploy:
      resources:
        limits:
          cpus: "0.25"     
    ports:
      - "3001:3001"
    
    restart: unless-stopped
    networks:
      - rabbitmq_net
    

  short-urlconverter:
    image: ${DOCKER_USERNAME}/url-shorturl-converter:latest
    container_name: shorturl-converter
    env_file:
      - env.compose  
    ports:
      - "3011:3011"
    networks:
      - rabbitmq_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
    depends_on:
      - rabbitmq
      - nats
    
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}

      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit loopback_users []"
      RABBITMQ_HIPE_COMPILE: 0

      # RABBITMQ_NODENAME: rabbit@rabbitmq
      # RABBITMQ_USE_LONGNAME: "false"
    ports:
      # Expose for local dev
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    deploy:
      resources:
        limits:
          cpus: "1"
    depends_on:
      - http-server  

    networks:
      - rabbitmq_net
  nats:
    image: nats:2.10
    container_name: nats-server
    ports:
      - "4222:4222"
      # - "8222:8222"
      # - "6222:6222"
    volumes:
      - ./nats_data:/data
      - ./nats-server.conf:/etc/nats/nats-server.conf
    command: ["-c", "/etc/nats/nats-server.conf"]

    deploy:
      resources:
        limits:
          cpus: "0.75"
    restart: unless-stopped
    networks:
      - rabbitmq_net

volumes:
  rabbitmq_data:
  nats_data:
  
networks:
  rabbitmq_net:
    driver: bridge
