FROM node:22 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=shorturl-converter
WORKDIR /app
COPY . .
RUN turbo prune --scope=${APP} --docker
FROM base AS installer
ARG APP=shorturl-converter
WORKDIR /app
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP} --force
RUN pnpm --filter types run build
RUN pnpm --filter mongodb run build
RUN pnpm --filter nats-server run build
RUN pnpm --filter rabbitmq run build
# FROM BASE AS BUILDER
# WORKDIR /app
# ARG APP=ws-server 
# COPY --from=INSTALLER /app ./
# WORKDIR /app/apps/${APP}
# RUN pnpm run build
FROM base AS runner
ARG APP=shorturl-converter 
WORKDIR /app
COPY --from=installer /app  ./
WORKDIR /app/apps/${APP}

EXPOSE 3011
CMD ["pnpm", "run", "dev"]  
