FROM node:22 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=shorturl-converter
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM base AS installer
WORKDIR /app
ARG APP=shorturl-converter
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY package-lock.json ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}
#   "build" "pnpm --recursive run build && <name> build" in package.json or manualy build the dependency


FROM base AS builder
ARG APP=shorturl-converter
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm run build
RUN pnpm --filter=${APP} deploy /app-prod --prod

FROM node:22-slim AS runner
ARG APP=shorturl-converter
WORKDIR /app
COPY --from=builder /app/app-prod ./
WORKDIR /app/apps/${APP}
EXPOSE 3011
CMD ["pnpm", "run", "start"] 
