FROM node:22 AS  base

ENV PATH=/app/node_modules/.bin:$PATH
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=analytics
WORKDIR /app
COPY . .
RUN turbo prune --scope=${APP} --docker

FROM base AS installer
ARG APP=analytics
WORKDIR /app
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json  ./
COPY pnpm-lock.yaml ./
COPY  pnpm-workspace.yaml ./
COPY apps/${APP}/package.json ./apps/${APP}/
COPY .npmrc ./
COPY packages/ ./packages/
RUN pnpm install --filter ${APP}

FROM base AS  builder
ARG APP=analytics
ARG NEXT_PUBLIC_ANALYTICS_FRONTEND_URL
ARG NEXT_PUBLIC_BACKEND_URL
WORKDIR /app
ENV NEXT_PUBLIC_ANALYTICS_FRONTEND_URL=${NEXT_PUBLIC_ANALYTICS_FRONTEND_URL}
ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
COPY --from=installer /app ./
COPY --from=installer /app/node_modules ./node_modules
WORKDIR /app/apps/${APP}
RUN pnpm --filter=${APP}... run build
RUN pnpm --filter=${APP} deploy /app/outdir --prod


FROM node:22-slim AS runner
ARG APP=analytics
WORKDIR /app
COPY --from=builder /app/outdir/. ./apps/${APP}/
COPY --from=builder /app/apps/${APP}/.next/standalone ./apps/${APP}/
COPY --from=builder /app/apps/${APP}/.next/static ./apps/${APP}/.next/static
COPY --from=builder /app/apps/${APP}/public ./apps/${APP}/public
WORKDIR /app/apps/${APP}
EXPOSE 3006
CMD ["node", "server.js"]

