FROM node:22 as BASE
RUN npm install -g pnpm turbo

FROM BASE AS prunner
ARG APP=http-server
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM BASE AS installer
WORKDIR /app
ARG APP=http-server
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}

#   "build" "pnpm --recursive run build && next build" in package.json or manualy build the dependency

FROM BASE AS builder
ARG APP=http-server
ARG NEXT_PUBLIC_FRONTEND_URL
WORKDIR /app
ENV APP=http-server
ENV NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm run build
RUN pnpm --filter=${APP} deploy /app/outdir --prod

FROM node:22-slim AS runner
ARG APP=http-server
WORKDIR /app
COPY --from=builder /app/outdir/. ./apps/${APP}/
WORKDIR /app/apps/${APP}
EXPOSE 3001
CMD ["pnpm", "run", "start"] 
