FROM node:22 as BASE
RUN npm install -g pnpm turbo

FROM BASE AS prunner
ARG APP=http-server
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM BASE AS installer
WORKDIR /app
ARG APP=http-server
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY package-lock.json ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}
RUN pnpm --filter types run build
RUN pnpm --filter mongodb run build
RUN pnpm --filter nats-server run build
RUN pnpm --filter rabbitmq run build
RUN pnpm --filter radisclient run build    

FROM BASE AS builder
ARG APP=http-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm run build
RUN pnpm --filter=${APP} deploy /app-prod --prod

FROM node:22-slim AS runner
ARG APP=http-server
WORKDIR /app
COPY --from=builder /app/app-prod ./
WORKDIR /app/apps/${APP}
EXPOSE 3001
CMD ["pnpm", "run", "start"] 
