FROM node:22 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=data-collector
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM base AS installer
WORKDIR /app
ARG APP=data-collector
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY package-lock.json ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}
RUN pnpm --filter types run build
RUN pnpm --filter mongodb run build
RUN pnpm --filter nats-server run build
RUN pnpm --filter rabbitmq run build

FROM base AS builder
ARG APP=data-collector
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm run build
RUN pnpm --filter=${APP} deploy /app-prod --prod

FROM node:22-slim AS runner
ARG APP=data-collector
WORKDIR /app
COPY --from=builder /app/app-prod ./
WORKDIR /app/apps/${APP}
EXPOSE 3012
CMD ["pnpm", "run", "start"] 