FROM node:22 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=ws-server
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM base AS installer
WORKDIR /app
ARG APP=ws-server
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}

#   "build" "pnpm --recursive run build && <name> build" in package.json or manualy build the dependency
FROM base AS builder
ARG APP=ws-server
ARG NEXT_PUBLIC_FRONTEND_URL
WORKDIR /app
ENV NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm --filter=${APP}... run build
RUN pnpm --filter=${APP} deploy /app/outdir --prod

FROM node:22-slim AS runner
ARG APP=ws-server
WORKDIR /app
COPY --from=base /usr/local/bin/pnpm /usr/local/bin/pnpm
COPY --from=builder /app/outdir/. ./apps/${APP}/
WORKDIR /app/apps/${APP}
EXPOSE 8080
CMD ["pnpm", "run", "start"] 
