on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: staging
    env:
      NEXT_PUBLIC_ANALYTICS_FRONTEND_URL: ${{secrets.NEXT_PUBLIC_ANALYTICS_FRONTEND_URL}}
      NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL}}
      NEXT_PUBLIC_FRONTEND_URL: ${{secrets.NEXT_PUBLIC_FRONTEND_URL}}
      NEXT_PUBLIC_WS_SERVER_URL: ${{secrets.NEXT_PUBLIC_WS_SERVER_URL}}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push url-web image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/web/dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-web:latest
            ${{ secrets.DOCKER_USERNAME }}/url-web:${{env.COMMIT_SHA}}

          build-args: |
            NEXT_PUBLIC_FRONTEND_URL=${{env.NEXT_PUBLIC_FRONTEND_URL}}
            NEXT_PUBLIC_BACKEND_URL=${{env.NEXT_PUBLIC_BACKEND_URL}}
            NEXT_PUBLIC_WS_SERVER_URL=${{env.NEXT_PUBLIC_WS_SERVER_URL}}

      - name: build and push url-analytics image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/analytics/dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-analytics:latest
            ${{ secrets.DOCKER_USERNAME }}/url-analytics:${{env.COMMIT_SHA}}

          build-args: |
            NEXT_PUBLIC_ANALYTICS_FRONTEND_URL=${{env.NEXT_PUBLIC_ANALYTICS_FRONTEND_URL}}
            NEXT_PUBLIC_BACKEND_URL=${{env.NEXT_PUBLIC_BACKEND_URL}}

      - name: build and push data-collector image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/data-collector/dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-data-collector:latest
            ${{ secrets.DOCKER_USERNAME }}/url-data-collector:${{env.COMMIT_SHA}}

      - name: build and push http-server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/http-server/dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-http-server:latest
            ${{ secrets.DOCKER_USERNAME }}/url-http-server:${{env.COMMIT_SHA}}

          build-args: |
            NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL

      - name: build and push shorturl-converter image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/shorturl-converter/dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-shorturl-converter:latest
            ${{ secrets.DOCKER_USERNAME }}/url-shorturl-converter:${{env.COMMIT_SHA}}

          build-args: |
            NEXT_PUBLIC_FRONTEND_URL=${{env.NEXT_PUBLIC_FRONTEND_URL}}

      - name: build and push ws-server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/ws-server/dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/url-ws-server:latest
            ${{ secrets.DOCKER_USERNAME }}/url-ws-server:${{env.COMMIT_SHA}}

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate Nginx config from template
        run: |
          mkdir -p build
          chmod 777 build
          export API_DOMAIN=${{ secrets.API_DOMAIN }}
          export FRONTEND_DOMAIN=${{ secrets.FRONTEND_DOMAIN }}
          export WS_SERVER_DOMAIN=${{ secrets.WS_SERVER_DOMAIN }}
          export API_DOMAIN_PORT=${{ secrets.API_DOMAIN_PORT }}
          export FRONTEND_DOMAIN_PORT=${{ secrets.FRONTEND_DOMAIN_PORT }}
          export WS_SERVER_DOMAIN_PORT=${{ secrets.WS_SERVER_DOMAIN_PORT }}
          export ANALYTICS_DOMAIN=${{secrets.ANALYTICS_DOMAIN}}
          export ANALYTICS_DOMAIN_PORT=${{secrets.ANALYTICS_DOMAIN_PORT}}
          envsubst '${API_DOMAIN} ${FRONTEND_DOMAIN} ${WS_SERVER_DOMAIN} ${ANALYTICS_DOMAIN} ${API_DOMAIN_PORT} ${FRONTEND_DOMAIN_PORT} \
          ${WS_SERVER_DOMAIN_PORT} ${ANALYTICS_DOMAIN_PORT}' \
          < nginx/nginx.conf.template > ./build/nginx.conf

      - name: Copy config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/*"
          target: "~/nginx-temp"

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.staging.yaml"
          target: "/home/${{ secrets.SERVER_USER }}"

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export API_DOMAIN="${{ secrets.API_DOMAIN }}"
            export FRONTEND_DOMAIN="${{ secrets.FRONTEND_DOMAIN }}"
            export WS_SERVER_DOMAIN="${{ secrets.WS_SERVER_DOMAIN }}"
            export ANALYTICS_DOMAIN="${{secrets.ANALYTICS_DOMAIN}}"
            export USER="${{secrets.USER}}"
            export PASS="${{secrets.PASS}}"
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME}}"
            export RABBITMQ_USER="${{secrets.USER}}"
            export RABBITMQ_PASS="${{secrets.PASS}}"
            export NATS_SERVER="${{secrets.NATS_SERVER}}"
            export NATS_SERVER_NAME="${{secrets.NATS_SERVER_NAME}}"
            export jwt_public_key="${{secrets.JWT_PUBLIC_KEY}}"
            export jwt_private_key="${{secrets.JWT_PRIVATE_KEY}}"
            export INDENTITY_KEY="${{secrets.INDENTITY_KEY}}"
            export EXPECTED_AUD="${{secrets.EXPECTED_AUD}}"
            export JWT_ALGO="${{secrets.JWT_ALGO}}"
            export AUTH_ISSUER="${{secrets.AUTH_ISSUER}}"

            if ! command -v curl &> /dev/null; then
                sudo apt-get update
                sudo apt-get install -y curl
            fi

            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js already installed: $(node -v)"
            fi

            sudo apt-get install ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update

            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo groupadd docker

            sudo usermod -aG docker $USER

            sudo apt-get update -y
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo mkdir -p /etc/nginx/conf.d
            sudo cp -f /home/ubuntu/nginx-temp/build/nginx.conf /etc/nginx/conf.d/app.conf
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo rm -f /etc/nginx/sites-available/default
            sudo apt install certbot python3-certbot-nginx -y

            sudo certbot --nginx -d ${{secrets.FRONTEND_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive
            sudo certbot --nginx -d ${{secrets.API_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive
            sudo certbot --nginx -d ${{secrets.WS_SERVER_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive
            sudo certbot --nginx -d ${{secrets._ANALYTICS_DOMAIN}} -m ${{ secrets.SSL_EMAIL }} --agree-tos --non-interactive

            sudo certbot renew --deploy-hook "systemctl reload nginx"
            sudo nginx -t
            sudo systemctl reload nginx

            echo "Stopping all containers..."
            if [ -n "$(sudo docker ps -q)" ]; then
            sudo docker stop $(sudo docker ps -q) || true
            fi

            sleep 5

            echo "Removing all containers..."
            if [ -n "$(sudo docker ps -aq)" ]; then
            sudo docker rm -f $(sudo docker ps -aq) || true
            fi

            docker compose -f docker-compose.staging.yaml down --remove-orphans || true
            sudo docker image prune -f || true
            sudo docker prune -af || true

            echo "Pulling the  images from  docker hub"
            cat << EOF > nats-server.conf

            server_name: ${NATS_SERVER_NAME}
              authorization {
              user: ${USER}
              password: ${PASS}
              timeout: 5
            }

            listen: 0.0.0.0:4222
            debug: true
            trace: false
            logtime: true

            max_connections: 1000
            max_payload: 67108864
            write_deadline: 5s

            http: 0.0.0.0:8222
            jetstream {
              store_dir: /data/jetstream
              max_mem: 209715200
              max_file: 429496729
            }
            EOF

            sudo mkdir -p rabbitmq_data
            sudo mkdir -p nats_data
            sudo mkdir -p rabbitmq
            sudo chown -R 1001:1001 rabbitmq_data
            sudo chown -R 1001:1001 nats_data
            sudo chown -R 1001:1001 rabbitmq

            cat <<'RAB'> enabled_plugins
            [rabbitmq_auth_backend_jwt].
            RAB

            echo "$jwt_public_key" | sudo tee rabbitmq/jwt_public_key.pem > /dev/null
            sudo chmod 600 rabbitmq/jwt_public_key.pem

            sudo mv enabled_plugins rabbitmq/enabled_plugins
            sudo chmod 644 rabbitmq/enabled_plugins
            sudo chmod 644 rabbitmq/rabbitmq.conf
            
            cat << RABCONF > rabbitmq.conf
            auth_backends.1 = rabbit_auth_backend_jwt
            auth_backends.2 = internal
            auth_jwt.signing_key= /etc/rabbitmq/jwt_public_key.pem
            auth_jwt.algorithm = ${JWT_ALGO}
            auth_jwt.claims_identity_key = ${INDENTITY_KEY}
            auth_jwt.expected_iss =${AUTH_ISSUER}
            auth_jwt.expected_aud =${EXPECTED_AUD}
            auth_jwt.verify=true
            RABCONF

            sudo mv rabbitmq.conf  rabbitmq/rabbitmq.conf

            rm -f env.compose || true

            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> env.compose
            echo "RABBITMQ_USER=${{ secrets.USER }}" >> env.compose
            echo "RABBITMQ_PASS=${{ secrets.PASS }}" >> env.compose
            echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> env.compose
            echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}" >> env.compose
            echo "NEXT_PUBLIC_ANALYTICS_FRONTEND_URL=${{secrets.NEXT_PUBLIC_ANALYTICS_FRONTEND_URL}}" >> env.compose
            echo "NEXT_PUBLIC_WS_SERVER_URL=${{ secrets.NEXT_PUBLIC_WS_SERVER_URL }}" >> env.compose
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> env.compose
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> env.compose
            echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> env.compose
            echo "api_key=${{ secrets.API_KEY }}" >> env.compose
            echo "groq_api_key=${{ secrets.GROQ_API_KEY }}" >> env.compose
            echo "access_key=${{ secrets.ACCESS_KEY }}" >> env.compose
            echo "secret_key=${{ secrets.SECRET_KEY }}" >> env.compose
            echo "RABBITMQ_CLUSTER_URL=${{ secrets.RABBITMQ_CLUSTER_URL1 }}" >> env.compose
            echo "DB_URL=${{ secrets.DB_URL }}" >> env.compose
            echo "TOPIC1=${{ secrets.TOPIC1 }}" >> env.compose
            echo "EXCHANGE_NAME1=${{ secrets.EXCHANGE_NAME1 }}" >> env.compose
            echo "BINDING_KEY1=${{ secrets.BINDING_KEY1 }}" >> env.compose
            echo "ROUTING_KEY1=${{ secrets.ROUTING_KEY1 }}" >> env.compose
            echo "QUEUE_NAME1=${{ secrets.QUEUE_NAME1 }}" >> env.compose
            echo "TOPIC2=${{ secrets.TOPIC2 }}" >> env.compose
            echo "EXCHANGE_NAME2=${{ secrets.EXCHANGE_NAME2 }}" >> env.compose
            echo "BINDING_KEY2=${{ secrets.BINDING_KEY2 }}" >> env.compose
            echo "ROUTING_KEY2=${{ secrets.ROUTING_KEY2 }}" >> env.compose
            echo "QUEUE_NAME2=${{ secrets.QUEUE_NAME2 }}" >> env.compose
            echo "URL_CHANNAL=${{ secrets.URL_CHANNAL }}" >> env.compose
            echo "URL_STATUS=${{ secrets.URL_STATUS }}" >> env.compose
            echo "user=${{ secrets.USER }}" >> env.compose
            echo "pass=${{ secrets.PASS }}" >> env.compose
            echo "servers=${{ secrets.NATS_SERVER }}" >> env.compose
            echo "jwt_private_key='${{ secrets.JWT_PRIVATE_KEY }}'" >> env.compose
            echo "INDENTITY_KEY=${{ secrets.INDENTITY_KEY }}" >> env.compose
            echo "AUTH_ISSUER=${{ secrets.AUTH_ISSUER }}" >> env.compose
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> env.compose
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> env.compose
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> env.compose

            sudo docker compose -f docker-compose.staging.yaml --env-file env.compose pull
            sudo docker compose -f docker-compose.staging.yaml --env-file env.compose up -d
